pipeline_version: feature/firestarter_prodigy
git_url: https://github.com/vonnetworking/pipeline_lib_test_project.git
git_branch: master
build_tool: maven
maven_version: 3.6.3
maven_goals: "clean install"
